version: '3.7'

services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Монтируем ТОЛЬКО результаты и отчеты, НЕ весь код!
      - ./allure-results:/usr/workspace/allure-results
      - ./allure-report:/usr/workspace/allure-report
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}
    # command удаляем - будем указывать команду при запуске